SELECT I.ID AS ID, NI.FISH_NAME AS FISH_NAME, I.LENGTH AS LENGTH
FROM FISH_INFO I
JOIN FISH_NAME_INFO NI ON I.FISH_TYPE = NI.FISH_TYPE
WHERE I.LENGTH = (
    SELECT MAX(LENGTH) 
    FROM FISH_INFO I2 
    JOIN FISH_NAME_INFO NI2 ON I2.FISH_TYPE = NI2.FISH_TYPE 
    WHERE NI2.FISH_NAME = NI.FISH_NAME
);